FROM golang:1.21-alpine3.18 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY main.go ./
RUN go build -o gateway

FROM alpine:3.18
WORKDIR /app
COPY --from=builder /app/gateway .

EXPOSE 8080
CMD ["/app/gateway"]